### ISSUE TITLE
NTR/TWL card implementation tracking issue

### ISSUE THREAD

**Issue by angelsl** [angelsl/libncgc#1]
## NTR
* [ ] Support `chipid & 0x80000000` set cards
* [ ] Software KEY2
* [ ] Add function for decrypting the encrypted secure area
* [x] Add convenience functions for the standard card commands (0xB7 read data)
* [x] C++ wrapper
* [ ] Cleanup blowfish code

## TWL
* [ ] Support DSi carts
